package si.uni.fri.sprouty.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

// --- 1. PLANT ENTITY ---

/**
 * Represents a single user-owned plant instance in the local Room database.
 */
@Entity(tableName = "plants")
data class Plant(
    // --- IDs and References ---
    @PrimaryKey(autoGenerate = true)
    val localId: Long = 0,
    val firebaseId: String? = null,
    val speciesName: String,

    // --- User Customization & Status ---
    val customName: String? = null,
    val plantedDate: Long,
    val lastWatered: Long,
    val userPictureUrl: String? = null,

    // --- Health & Growth Tracking ---
    val healthStatus: String,
    val currentGrowthStage: String,
    val notes: String? = null,

    // --- Sensor & Notification Data ---
    val notificationsEnabled: Boolean = true,
    val connectedSensorId: String? = null,
    val lastSensorDataUrl: String? = null,

    val targetWateringInterval: Int,
    val requiredLightLevel: String
)

// --- 2. PLANT DAO (Data Access Object) ---

data class PlantIdentificationResponse(
    @SerializedName("userPlant")
    val userPlant: UserPlant,

    @SerializedName("masterData")
    val masterData: MasterPlantData
)

/**
 * The specific instance of the plant in the user's garden.
 */
data class UserPlant(
    val id: String? = null,
    val ownerId: String? = null,
    val speciesId: String? = null,
    val speciesName: String? = null,
    val customName: String? = null,
    val plantedDate: Long = 0,
    val lastWatered: Long = 0,
    val targetWateringInterval: Int = 0,
    val healthStatus: String? = null,
    val currentGrowthStage: String? = null,
    val requiredLightLevel: String? = null
)

/**
 * The global botanical data generated by OpenAI.
 */
data class MasterPlantData(
    val speciesName: String,
    val type: String,
    val life: String,
    val fruit: String,
    val uses: List<String>,
    val fact: String,
    val tox: String,
    val minT: Int,
    val maxT: Int,
    val light: String,
    val soilH: String,
    val airH: String,

    @SerializedName("water_interval") // Match Spring field
    val water: Int,

    val growth: String,
    val soil: String,

    @SerializedName("maxHeight") // Match Spring field
    val maxH: Int
)