package si.uni.fri.sprouty.data.network

import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Url

// --- Data Transfer Objects (DTOs) ---

/**
 * Request body for Firebase Google sign-in flow.
 * Contains the token generated by the Firebase SDK.
 */
data class GoogleLoginRequest(
    val idToken: String
)

/**
 * Request body for standard Email/Password registration.
 */
data class RegisterRequest(
    val email: String,
    val password: String,
    val displayName: String
)

/**
 * Expected response body for successful authentication (login or register).
 * Contains the internal JWT token and the user's unique Firebase ID.
 */
data class AuthResponse(
    val firebaseUid: String,
    val token: String // The actual JWT token
)

/**
 * Expected response body when fetching the user's profile data.
 */
data class UserDataResponse(
    val name: String,
    val email: String
)


/**
 * Retrofit interface for authentication and user-related endpoints.
 */
interface AuthApiService {

    // --- Authentication ---

    /**
     * Exchanges a Firebase ID Token for our internal JWT token using Google Sign-In.
     * Endpoint: POST /users/login/google
     */
    @POST("users/login/google")
    suspend fun loginWithGoogle(@Body request: GoogleLoginRequest): Response<AuthResponse>

    /**
     * Registers a new user with Email/Password and creates a session.
     * Endpoint: POST /users/register
     */
    @POST("users/register")
    suspend fun register(@Body request: RegisterRequest): Response<AuthResponse>

    /**
     * Generic endpoint for exchanging a Firebase token for a JWT for other login methods
     * (e.g., standard email login after successful Firebase sign-in).
     * The full path is specified dynamically via the @Url annotation.
     */
    @POST
    suspend fun exchangeToken(
        @Url url: String, // Accepts the full path, e.g., "users/login/email"
        @Body request: GoogleLoginRequest // Note: This request is used for all Firebase token exchanges
    ): Response<AuthResponse>

    // --- User Data ---

    /**
     * Retrieves the current user's profile data.
     * This call requires a valid JWT in the Authorization header (handled by AuthInterceptor).
     * Endpoint: GET /user/data
     */
    @GET("user/data")
    suspend fun getUserData(): Response<UserDataResponse>
}