package si.uni.fri.sprouty.data.network

import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.PATCH
import retrofit2.http.POST
import retrofit2.http.Url

// --- Data Transfer Objects (DTOs) ---

data class UpdateFcmRequest(
    val fcmToken: String
)

/**
 * Request body for Firebase Google sign-in flow.
 * Contains the token generated by the Firebase SDK.
 */
data class GoogleLoginRequest(
    val idToken: String,
    val fcmToken: String? = null // Add this
)

/**
 * Request body for standard Email/Password registration.
 */
data class RegisterRequest(
    val email: String,
    val password: String,
    val displayName: String,
    val fcmToken: String? = null // Add this
)

/**
 * Expected response body for successful authentication (login or register).
 * Contains the internal JWT token and the user's unique Firebase ID.
 */
data class AuthResponse(
    val firebaseUid: String,
    val token: String // The actual JWT token
)

/**
 * Expected response body when fetching the user's profile data.
 */
data class UserDataResponse(
    val name: String,
    val email: String
)


/**
 * Retrofit interface for authentication and user-related endpoints.
 */
interface AuthApiService {

    // --- Authentication ---

    @PATCH("users/update-fcm")
    suspend fun updateFcmToken(@Body request: UpdateFcmRequest): Response<Unit>

    @POST("users/login/google")
    suspend fun loginWithGoogle(@Body request: GoogleLoginRequest): Response<AuthResponse>

    @POST("users/register")
    suspend fun register(@Body request: RegisterRequest): Response<AuthResponse>

    @POST
    suspend fun exchangeToken(
        @Url url: String,
        @Body request: GoogleLoginRequest
    ): Response<AuthResponse>

    /**
     * Notifies the backend to delete all user-related documents in Firestore
     * and files in Cloud Storage before the Firebase Auth account is destroyed.
     */
    // This matches your @DeleteMapping("/me") in the UserController
    @DELETE("users/me")
    suspend fun deleteAccount(): Response<Unit>
}